# Advanced Python Exercises

## Welcome to the Advanced Python Exercises!

This notebook is designed for students who are already familiar with basic Python programming concepts. It covers more advanced topics, including list comprehensions, decorators, generators, and data manipulation with Pandas and NumPy.

### Exercise 1: List Comprehensions with Conditions

In [1]:

# List Comprehension with Conditions
# TODO: Complete the code below by filling in the missing parts

# Step 1: Create a list of squares of even numbers from 1 to 20
squares = [x**2 for x in range(1, 21) if x % 2 == 0]

# Step 2: Create a list of words that start with the letter 'a'
words = ["apple", "banana", "avocado", "cherry", "apricot"]
a_words = [word for word in words if word.startswith('a')]

# Step 3: Print the results
print("Squares of even numbers:", squares)
print("Words that start with 'a':", a_words)
        

Squares of even numbers: [4, 16, 36, 64, 100, 144, 196, 256, 324, 400]
Words that start with 'a': ['apple', 'avocado', 'apricot']


### Exercise 2: Decorators

In [2]:

# Python Decorators
# TODO: Complete the code below by filling in the missing parts

# Step 1: Define a decorator that logs the execution time of a function
import time

def timer_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Execution time: {end_time - start_time} seconds")
        return result
    return wrapper

# Step 2: Apply the decorator to a function that calculates the factorial of a number
@timer_decorator
def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

# Step 3: Test the decorated function
print("Factorial of 10:", factorial(10))
        

Execution time: 2.86102294921875e-06 seconds
Factorial of 10: 3628800


### Exercise 3: Generators

In [3]:

# Python Generators
# TODO: Complete the code below by filling in the missing parts

# Step 1: Define a generator function that yields the Fibonacci sequence
def fibonacci_sequence(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

# Step 2: Use the generator to print the first 10 Fibonacci numbers
fib_gen = fibonacci_sequence(10)
print("First 10 Fibonacci numbers:")
for num in fib_gen:
    print(num)
        

First 10 Fibonacci numbers:
0
1
1
2
3
5
8
13
21
34


### Exercise 4: Advanced NumPy Operations

In [5]:
%pip install numpy
import numpy as np

# Advanced NumPy Operations
# TODO: Complete the code below by filling in the missing parts

# Step 1: Create a 3x3 matrix with values ranging from 1 to 9
matrix = np.arange(1, 10).reshape(3, 3)

# Step 2: Calculate the determinant of the matrix
determinant = np.linalg.det(matrix)

# Step 3: Calculate the inverse of the matrix
inverse = np.linalg.inv(matrix)

# Step 4: Print the results
print("Matrix:")
print(matrix)
print("Determinant:", determinant)
print("Inverse:")
print(inverse)
        

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 32.8 MB/s eta 0:00:0000:0100:01
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant: -9.51619735392994e-16
Inverse:
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


### Exercise 5: Data Analysis with Pandas

In [6]:

%pip install pandas
import pandas as pd

# Data Analysis with Pandas
# TODO: Complete the code below by filling in the missing parts

# Step 1: Create a DataFrame from a dictionary of lists
data = {
    "Name": ["John", "Anna", "Peter", "Linda", "James"],
    "Age": [28, 22, 35, 32, 30],
    "Salary": [50000, 54000, 58000, 62000, 52000]
}
df = pd.DataFrame(data)

# Step 2: Add a new column 'Bonus' that is 10% of the Salary
df['Bonus'] = df['Salary'] * 0.1

# Step 3: Filter the DataFrame to only include employees with a Salary greater than 55000
high_salary_df = df[df['Salary'] > 55000]

# Step 4: Print the original DataFrame and the filtered DataFrame
print("Original DataFrame:")
print(df)
print("Filtered DataFrame (Salary > 55000):")
print(high_salary_df)
        

  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 51.9 MB/s eta 0:00:0000:010:01
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Note: you may need to restart the kernel to use updated packages.
Original DataFrame:
    Name  Age  Salary   Bonus
0   John   28   50000  5000.0
1   Anna   22   54000  5400.0
2  Peter   35   58000  5800.0
3  Linda   32   62000  6200.0
4  James   30   52000  5200.0
Filtered DataFrame (Salary > 55000):
    Name  Age  Salary   Bonus
2  Peter   35   58000  5800.0
3  Linda   32   62000  6200.0


### Exercise 6: Handling Missing Data with Pandas

In [9]:

# Handling Missing Data with Pandas
# TODO: Complete the code below by filling in the missing parts

# Step 1: Create a DataFrame with missing values
data_with_nan = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [24, 27, np.nan, 22, 29],
    "Salary": [50000, np.nan, 58000, 62000, 52000]
}
df_nan = pd.DataFrame(data_with_nan)

# Step 2: Fill the missing values in 'Age' with the mean age
df_nan['Age'].fillna(df_nan['Age'].mean(), inplace=True)

# Step 3: Drop rows where any value is missing
df_cleaned = df_nan.dropna()

# Step 4: Print the cleaned DataFrame
print("DataFrame after filling missing values and dropping rows with any missing data:")
print(df_cleaned)
        

DataFrame after filling missing values and dropping rows with any missing data:
      Name   Age   Salary
0    Alice  24.0  50000.0
2  Charlie  25.5  58000.0
3    David  22.0  62000.0
4      Eve  29.0  52000.0


/var/folders/6y/wkyxtwb91ms1vgj1flry6l0hvvkbvq/T/ipykernel_88989/287230391.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_nan['Age'].fillna(df_nan['Age'].mean(), inplace=True)


### Wrap-Up

Great work! You've completed the advanced Python exercises. These exercises have covered key concepts that will be useful as we move into more complex topics in the workshop.